### ISSUE TITLE
K-means 과제 질문입니다

### ISSUE THREAD

**Issue by hwanginsun** [public-ai/ALAI_Homework#24]
[insun_week4_answer.zip](https://github.com/public-ai/ALAI_Homework/files/3117795/insun_week4_answer.zip)

질문1 : 이전point정보와 지금의 정보가 같으면 for문을 탈출하고 싶습니다. 
             IF문이 정상작동하려면 어떻게 해야 하나요?

질문2 : 아래의 scatter메소드에서, colors부분의 인자로 combine_list_의 3번째 열의 정보를 넣고 싶습니다. 
하지만 스칼라가 아니라고 에러가 납니다. 제가 어떤 부분을 잘못하고 있나요?
        idx = tf.cast(combine_list_[:,2], dtype=tf.int32)
        plt.scatter(combine_list_[:,0], combine_list_[:,1], label='dataset', c=colors[idx])
        

질문3 : 아래 식을 실행하면 에러메시지에서  tf.map_fn.을 쓰라고 하는데, 
            이부분은 이해가 잘 되지 않습니다.
            plt.scatter(centroids[:,0], centroids[:,1], s=200, label="centroid", marker='+')

** 여기서는 노트북파일이 바로 업로드가 안되네요. zip으로 압축해서 업로드합니다.

**Comment by anthony0727** [comment]
질문1 : 
먼저, equality check를 해야하는데, 모든 원소에 대해서 해야하므로 np.all이라는 함수를 통해서 모든 ref의 원소들이 val의 원소들과 같은 값인지 확인 할 수 있습니다.

아래 작성하신 코드가 동작하게 하려면, 먼저 np.equal이라는 함수의 [문서](https://docs.scipy.org/doc/numpy/reference/generated/numpy.equal.html)를 살펴보시고,

return값이 인자의 shape과 같은것을 확인 할 수있으므로, if문에 사용하기에 적절하지 않은 것을 확인 할 수 있습니다.
```python3
if np.equal(prev_cluster_per_point, cluster_per_point_) == [True] :
    break
```
따라서 아래와 같이 작성하시면 되겠습니다.
```python3
if prev_clusters is None:
    prev_clusters = cluster_values
elif np.all(prev_clusters==cluster_values):
    break
```

질문2:
c는 scalar(하나의 값)만 받을수 있기 때문에, `colors[idx]`(값들)을 넘겨주셔서 에러가 납니다. loop를 돌아야 할 것 같습니다.
```python3
# ex
for color in colors[idx]:
    plt.scatter(combine_list_[:,0], combine_list_[:,1], label='dataset', c=color)
```

질문3:
`centroids[:,0], centroids[:,1]`는 tensor입니다. `centroids[:,0]_, centroids[:,1]_`를 넘겨주셔야 합니다.

<br>
이해 되셨으면 issue close해주시면 감사하겠습니다!

**Comment by hwanginsun** [comment]
해결했습니다. 감사합니다
