### ISSUE TITLE
Week5 Homework 질문입니다.

### ISSUE THREAD

**Issue by hwanginsun** [public-ai/ALAI_Homework#30]
[Week5_Homework3_One_VS_ALL_IrisClassifier.zip](https://github.com/public-ai/ALAI_Homework/files/3141809/Week5_Homework3_One_VS_ALL_IrisClassifier.zip)

안녕하세요.. Week5 과제 질문입니다.

**- Class없이 구현한 텐서플로 코드에서 질문입니다.**
1. tf.cond()를 사용하여 구현하려 했는데, 잘되지 않았습니다. 하기와 같이 구현하려면 어떻게 해야 하나요
![image](https://user-images.githubusercontent.com/30209848/57136604-4476fe00-6de8-11e9-878e-a4a4e41fbc3d.png)

2. 저장된 Weights들을 불러와 하기와 같이 구현하면 되는지 궁금합니다
![image](https://user-images.githubusercontent.com/30209848/57136701-991a7900-6de8-11e9-8029-e7e202e7ae78.png)

3. 전반적으로 코드가 잘 구현되었는지 확인 부탁드립니다. 결과만을 놓고 봤을때, Setosa의 학습결과는 좋고, 나머지 꽃들은 결과가 좋지 않은 것 같습니다.
![image](https://user-images.githubusercontent.com/30209848/57136922-3d042480-6de9-11e9-8997-bb37ade52a23.png)

**- Class로 구현한 텐스플로 코드에 대한 질문입니다.**
1. Class를 사용하여 구현하는 방법을 잘 모르겠습니다.
2. Class내부의 method들에서 다른 변수에 어떻게 접근해야하는지 궁금합니다.

**Comment by anthony0727** [comment]
1. `acc`가 아닌 `acc_`를 사용하시면 if문 사용가능합니다. 

2. 전체 training에서 가장 정확도가 높은 모델을 택하게 하시면 됩니다. 예를 들어, 전체 training epochs이 3000회라고 했을때, 1000회씩 나누어 3번 training을 한다고 가정하면, 3번의 training중 가장 높은 정확도를 달성한 모델을 택하시면 되겠습니다.

3. 네 정확도가 꼭 90%이상 나오리라는 보장은 없습니다. 이 과제에서는 versicolour의 정확도가 낮은 편입니다.

**- Class로 구현한 텐스플로 코드에 대한 질문입니다.**
1. Class를 사용하여 구현하는 방법을 잘 모르겠습니다.
2. Class내부의 method들에서 다른 변수에 어떻게 접근해야하는지 궁금합니다.

위 부분들은 질문이 모호한 것 같습니다. class의 구현단의 부분은 수업자료중 python관련 부분을 참고 하시면 될 것 같습니다. 그리고, self prefix를 붙히시면(ex. self.변수)로 선언하시게 되면, 클래스 내의 instance methods에게는 visible합니다.

code review는 시간이 조금 소요 될 예정입니다. 감사합니다.

**Comment by hwanginsun** [comment]
class는 예제 참고하여 다시 공부해보도록 하겠습니다. 감사합니다
