### ISSUE TITLE
Week5 Homework 질문2입니다

### ISSUE THREAD

**Issue by hwanginsun** [public-ai/ALAI_Homework#33]
Week5 Homework4에 대한 질문입니다(FeedForward Network구현)

1.  Model을 Save하고 Restore하는 과정중에 저장된 tensor를 불러오지 못하는 문제가 있습니다.
해결방안이 궁금합니다
![image](https://user-images.githubusercontent.com/30209848/57190216-04805a00-6f53-11e9-8bd8-c99890d7d4d0.png)
![image](https://user-images.githubusercontent.com/30209848/57190228-106c1c00-6f53-11e9-9e3a-14c7524593fe.png)

[Week5_Homework4_Tensorflow을_이용한_FeedForward_Network_구현하기.zip](https://github.com/public-ai/ALAI_Homework/files/3145241/Week5_Homework4_Tensorflow._._FeedForward_Network_.zip)

**Comment by anthony0727** [comment]
아래와 같이 호출 하시면 되겠습니다.
```python3
    xs = graph.get_tensor_by_name('input_layer/xs:0') # tensor이름은 :0
    ys = graph.get_tensor_by_name('input_layer/ys:0')
    pred = graph.get_tensor_by_name('output_layer/pred:0')
```

**Comment by hwanginsun** [comment]
해결했습니다. 감사합니다.
