### ISSUE TITLE
Regularization 개념질문입니다

### ISSUE THREAD

**Issue by hwanginsun** [public-ai/ALAI_Homework#49]
안녕하세요 Regularization에 대한 질문입니다.

**1. 아래의 정의가 맞는지 궁금합니다.**

정규화의 정의는 Generalization Error을 줄이는게 목적인데, Training error을 줄이지 않는다.  라고 Ian Goodfellow 라는 분이 말씀하셨는데요.

다른 말로 풀어 쓰면, Test data set의 error를 줄인다. 그러기 위해서는 model이 train set에 overfitting하는 것을 줄여야 한다. 
이것을 해결하기 위해서는 여러가지 정규화 방법을 통해 model을 generalization해줘야 한다(L1, L2정규화, data argumentation, dataset증가, drop-out 등의 기법으로)

**2. 아래 내용의 설명부탁드립니다 (이해가 잘 안됩니다ㅠㅠ)**
generalization error는 train - test error이다 
이말은.. bias를 줄이고 variance는 유지한다

제가 이해한 바로는... 
bias는 model이 trainset에서 오차가 크다는 것이고. bias를 줄인다는 것은 model이 dataset에 underfitted된 상태(훈련이 덜된 상태)이기 때문에 더 훈련을 해야 한다는 뜻같습니다.

variance는 model이 train과 testset간의 차이인데, 이것을 유지한다는 것은 model이 적절하게 훈련됬다는 상태라는 뜻 같습니다. 그래서 더이상 할 필요가 없어서 유지한다는것 같습니다.

그래서 train - test error는 validation error인데, train할때 validation set에 대한 model error의 오차를 줄인다는 뜻인가요??

**Comment by pai-plznw4me** [comment]
@hwanginsun 
1. 아래의 정의가 맞는지 궁금합니다.
→ 네 맞습니다. 
2. 아래 내용의 설명부탁드립니다 (이해가 잘 안됩니다ㅠㅠ)
→ bias 의 정의는 '편향되어있다' 라는 뜻 입니다. bias 의 정의가  `train dataset 에 overfitting 되어 있다` 라는 말과 동치가 아닙니다.  우리가 원하는 이상적인 함수가 f(x) 이고 우리가 예측한 모형이 g(x) 라고 가정한다면 
f(x) - g(x ) 의 크기가 커졌을때 우리는 bias 가 커진다고 이야기합니다. 
하지만 우리가 모형을 학습시키는건 train dataset 이고 그렇기 때문에 train dataset 에 모델이 맞게 편향될거라고 
가정하고 있습니다.  즉 bias 을 줄인다는건 우리가 원하는 이상적인 모델과 학습으로 만들어진 모델의 차이를 줄인다라는 뜻 입니다. 하지만 우리는 이상적인 모델을 찾을수 없기에 test 데이터셋에 적합한 모델을 이상적인 모델이라고 생각하는 것 뿐이죠.
`variance` 은 `변동성`을 의미합니다. 생각해 보면 분산이 큰 데이터셋은 멀리 분포해있고 분산이 작은 데이터셋은 좁게 분포합니다. 이것을 모델 관점으로 생각해 보면 실제 데이터를 x 을  넣으면 `예측값의 변동이 크다`는 것은 `분산이 작다` 라는 뜻이 될것입니다. 아래 그림에서 왜 L2 regularization 을 적용했을때 변동성이 유지 되는지 생각해 보세요 .
왼쪽 그림은 overfitting 되어 있는 상태이고 오른쪽은 L2 regularization 을 적용한 후 결과 입니다. 

![Imgur](https://i.imgur.com/NFZUkFt.png)

**Comment by hwanginsun** [comment]
이해했습니다. 감사합니다.
