### ISSUE TITLE
Week8 auto encoder  과제 

### ISSUE THREAD

**Issue by hwanginsun** [public-ai/ALAI_Homework#54]
[Week8_face_autoencoder.zip](https://github.com/public-ai/ALAI_Homework/files/3261533/Week8_face_autoencoder.zip)

code부분에 노이즈를 주어서 결과를 출력하라는게 문제같은데요
구현방법이 합니다.
![image](https://user-images.githubusercontent.com/30209848/59033092-d3bd7880-88a2-11e9-8ee5-ba7e8a1958ea.png)

그리고 이미지 두개이상을 합치는 방법도 궁금합니다.
![image](https://user-images.githubusercontent.com/30209848/59033146-f780be80-88a2-11e9-9f6b-f28a8bab17b9.png)

이 두부분을 제외하면 과제는 어느정도 완성한 상태입니다
![image](https://user-images.githubusercontent.com/30209848/59033178-0f584280-88a3-11e9-974d-a2259aeb0eb0.png)
![image](https://user-images.githubusercontent.com/30209848/59033193-17b07d80-88a3-11e9-862f-987644adacf2.png)
![image](https://user-images.githubusercontent.com/30209848/59033199-1c753180-88a3-11e9-88a6-a18f92448299.png)

**Comment by anthony0727** [comment]
코칭시간에 해결이 된 것 같습니다!

**Comment by hwanginsun** [comment]
감사합니
