### ISSUE TITLE
week9 과제 질문입니다(vgg net 구현)

### ISSUE THREAD

**Issue by hwanginsun** [public-ai/ALAI_Homework#66]
week9 과제인 vgg net 과제에 대한 질문입니다.
[Week10_VGG Net.zip](https://github.com/public-ai/ALAI_Homework/files/3293879/Week10_VGG.Net.zip)

1. 모델을 save하고 restore하는데 까지 성공했습니다.
<훈련은 제대로 하지 않고 정상적으로 동작하는 것만 확인했습니다>
-  Model A를 구현하고 모델결과를 save했습니다.
![image](https://user-images.githubusercontent.com/30209848/59560221-70bda580-9049-11e9-870c-f8c94f290182.png)
- Model B에서 불러온 정보 
![image](https://user-images.githubusercontent.com/30209848/59560235-95198200-9049-11e9-8032-ce7a30029e1f.png)
- Model B에서 이어서 훈련한 결과
![image](https://user-images.githubusercontent.com/30209848/59560239-a4003480-9049-11e9-9293-25d36bea7e53.png)

질문입니다. Model B에서 Optimizer를 Adam에서 Momentum으로 변경하고 싶은데,
변경하고 정보를  restore하면 momentum관련 부분이 초기화  되지 않았다고 합니다.
**초기화 방법이 궁금합니다.** (불러온 정보를 개별적으로 초기화 하는 방법도 궁금합니다)
![image](https://user-images.githubusercontent.com/30209848/59560273-2be63e80-904a-11e9-8faf-8ec1cff37f5b.png)
![image](https://user-images.githubusercontent.com/30209848/59560270-22f56d00-904a-11e9-91dd-afe40d67b580.png)

2. tensor board에서 train과 validation의 loss와 accruacy 정보를 보고 싶습니다.
tensor board에서 load가 안되는데 어디가 문제인지 궁금합니다.

**Comment by hwanginsun** [comment]
3. image에서 평균값 빼주는 방법도 궁금합니다.
channel별로 flatten해서 mean빼고 sigma로 나눠주면 될까요?
좀더 쉽게할 수 있는 방법이 있는지 궁금합니다

**Comment by pai-plznw4me** [comment]
# Note  
인선님 다음번 질문을 주실때 부탁드리고 싶은것이 있습니다. 

1. `모델을 불러왔다 `라고 하면 모델을 불러온 코드 부분을 아래와 같이 오려서 주세요. 
```
    # loading parameters
    saver.restore(sess, save_path='./model/vgg_net')
    # convolution_layer_1/kernel/Momentum <-- 얘를 초기화 하지 못함
```

2. 코드는  zip 으로 묶어서 올리는 방법은 좋은 방법이 아니라고 생각합니다. 전체 코드를 올리는 습관도 그렇게 좋은 습관은 아닌것 같다는 생각이 드네요. 해당 질문에 대한 코드 부분만 올려주시면 될 것 같아요! 
만약 전체 코드를 첨부하고 싶으시다면 쌤 코드를 깃에 올리시고 그 깃 페이지에 링크를 걸어주세요. 

3. 그리고 필요 없는 코드는 지워주세요.
```
# print('저장된 변수의 이름을 불러옵니다')
var_names = cp.list_variables('./model/vgg_net')   # 변수와 shape를 가져온다. 저장된 data와 index에서 가져온다.
#print('저장된 변수의 이름 {}'.format(var_names))

3. 인선님 그리고 model pretraining 하는 부분과 model reconstruct 하는 `ipynb` 파일을 따로 만들어서 분리해주세요. (6월17일까지 진행해주세요.)

# 값 불러오기
con_layer1_kernel  = cp.load_variable('./model/vgg_net' , 'convolution_layer_1/kernel')   
con_layer1_bias    = cp.load_variable('./model/vgg_net' , 'convolution_layer_1/bias')

con_layer2_kernel  = cp.load_variable('./model/vgg_net' , 'convolution_layer_2/kernel')   
con_layer2_bias    = cp.load_variable('./model/vgg_net' , 'convolution_layer_2/bias')

con_layer3_kernel1 = cp.load_variable('./model/vgg_net' , 'convolution_layer_3/kernel')   
con_layer3_bias1   = cp.load_variable('./model/vgg_net' , 'convolution_layer_3/bias')
con_layer3_kernel2 = cp.load_variable('./model/vgg_net' , 'convolution_layer_3/kernel_1')   
con_layer3_bias2   = cp.load_variable('./model/vgg_net' , 'convolution_layer_3/bias_1')

# print('con_layer1, kernel : {} bias : {}'.format(con_layer1_kernel[:1,:1,:1], con_layer1_bias[0]))
```

# 답변 
변경하고 정보를 restore하면 momentum관련 부분이 초기화 되지 않았다고 합니다.
초기화 방법이 궁금합니다. (불러온 정보를 개별적으로 초기화 하는 방법도 궁금합니다)

save.restore  을 사용한후 새롭게 만들어 복원할게 없는 새로운 변수에 대해 restore 을 하고 싶다면  아래와 같은 방법을 사용해야 합니다. 

```
with graph.as_default():
    with tf.variable_scope('initialization'):
        # 모든 variable 가져옴        
        global_vars = tf.global_variables()

        # Variable이 초기화되었는지 안되었는지 확인
        is_not_initialized = sess.run(
            [tf.is_variable_initialized(var) for var in global_vars])

        # Variable 중 초기화되지 않은것만 가져옴
        not_initialized_vars = [v for (v, f) in
                                zip(global_vars, is_not_initialized) if not f]

        # 초기화되지 않은 것이 있으면, 초기화시킴
        if len(not_initialized_vars):
            sess.run(tf.variables_initializer(not_initialized_vars))

```
하지만 위 방법을 지금은 추천하지 않습니다. 

모델을 이전 모델과 똑같이 그린다. -> 저장된 weights 을 불러온다.(type 은 numpy ) -> 불러온 weights 값을 
모델의 초기값으로 넣어준다. -> 모델의 학습 방법을 바꾼다. -> 학습 시킨다. 

이런 식의 논리를 구현했으면 하는 바램이였습니다. 위 방식으로 작성해 보세요. 

#2 
tensor board에서 train과 validation의 loss와 accruacy 정보를 보고 싶습니다.
tensor board에서 load가 안되는데 어디가 문제인지 궁금합니다.

코드에 문제는 없습니다. 아마 colab에서 ngrok 으로 통신을 어떠한 이유로 막혀진것 같은 생각이 듭니다. 
코드에는 문제점이 없습니다. 

![Imgur](https://i.imgur.com/Lpcpdy9.png)

실제로 쌤 학습한걸 제 노트북에서 돌려봤을때 위 그림과 같이 잘 나온다는걸 확인했습니다. 

---
확인 다 하셨으면 이슈 내려주세요. 질문 있으시면 다시 recomment 달아주세요.
