### ISSUE TITLE
vgg paper 질문입니다

### ISSUE THREAD

**Issue by hwanginsun** [public-ai/ALAI_Homework#76]
vgg 논문내용중에  아래에 캡쳐한 내용을 잘 모르겠습니다...

![image](https://user-images.githubusercontent.com/30209848/59665176-620ff380-91ed-11e9-9131-8175647cdfd3.png)
--> 요약하면,  image를 convolution하면 전체 이미지에 대해서 적용하는 것이고, 여기서 나온 class score map은 각각의 클래스에 대한 정보에 대한 vector를 담고 있다(이 내용이 맞나요??)

<br>

![image](https://user-images.githubusercontent.com/30209848/59665414-d0ed4c80-91ed-11e9-80f0-4e61b54a875f.png)
--> fully convolutional network는 이미지 크기를 지정안해서 모든 이미지에 적용할 수 있음.
--> **multi-crop-evaluation is complementary to dense evaluation due to different convolution boundary conditions**에 대한 부분이 이해가 안됩니다.
--> 그래서 receptive filed 영역이 넓어지고 더 많은 것을 함축한다

<br>

![image](https://user-images.githubusercontent.com/30209848/59665656-4b1dd100-91ee-11e9-96e4-b5750306fede.png)
--> **multi crop evaluation**에 대한 정의가 궁금합니다
--> **we hypothesize that this is due to a different treatment of convolution boundary
conditions**에 대한 부분이 이해가 안됩니다

**Comment by pai-plznw4me** [comment]
*질문 : 요약하면, image를 convolution하면 전체 이미지에 대해서 적용하는 것이고, 여기서 나온 class score map은 각각의 클래스에 대한 정보에 대한 vector를 담고 있다(이 내용이 맞나요??)*
**=>네 맞습니다. class score map 은 overfeat 알고리즘에서 나오는 개념입니다. 수업시간에 설명드리겠습니다.**

`Dense Evauation` 은 class score map` 을 추출하는 과정을 통해 평가하는 방법을 의미합니다. 
아직 정확한 개념을 알려드린적인 없습니다. 수업시간에 설명 드리겠습니다. 

`Multi Crop` 개념은 사진을 여러장 잘라서 평가하는 방법입니다. 
즉 하나의 사진을 여러장으로 쪼개서 평가하는 방법입니다. `Alexnet` 의 논문의 Evaluaiton 방법을 참조하세요. 

저 이야기는 `Multi Crop` 을 통해 image 을 crop 하면 정보의 손실이 있고 `dense evaluation` 을 사용하면 정보의 간섭이 있어서  그것들을 상호 보완하면 성능이 올라간다 라는 말입니다.<br> 아직 이해하시기 어려울텐데 실습을 하신다면 바로 이해가실거에요. 수업중에 다루고 숙제로 나갈 예정입니다 .<br> 또한  overfeat 알고리즘을 다룰때 심도 있게 다룰 예정입니다.<br> 우선 저 문장은 이정도로 이해하시고 넘어가시면 좋을것 같습니다. 

추가 질문 없으면 이슈 내려주세요

**Comment by hwanginsun** [comment]
확인했습니다
