### ISSUE TITLE
인선님 코드 정리 요청 

### ISSUE THREAD

**Issue by pai-plznw4me** [public-ai/ALAI_Homework#78]
## 코드 정리가 너무 안되어 있습니다!  코드 정리 다시해주세요. 
1.   [정리 요청 코드 1](https://github.com/public-ai/ALAI_Homework/blob/master/homework/week_9/insun/Week09_vgg_net_modelB.ipynb) || [정리 요청 코드 2](https://github.com/public-ai/ALAI_Homework/blob/master/homework/week_9/insun/Week09_vgg_net_modelB.ipynb)

2. 표는 markdown 으로 작성해주세요. <br>[해당 링크](https://github.com/public-ai/ALAI_Homework/blob/master/homework/week_9/Homework_Pretraining.ipynb) 로 들어가시면 markdown 으로 표를 작성하시는 예제가 있습니다. 

## 요청 이유
1.  코드가 너무 길어져 아래와 같은 현상이 발생됩니다.  
![Imgur](https://i.imgur.com/xrnoxxQ.png) 

2. 필요 없는 주석이 너무 많습니다. 
![Imgur](https://i.imgur.com/NFi4zM8.png)

확인하셨으면 issue 내려 주세요.

**Comment by hwanginsun** [comment]
확인했습니다
